# Generated by Django 6.0 on 2026-01-20 15:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 3),
                            ("about", 6),
                            ("services", 12),
                            ("showcase", 17),
                            ("contact", 20),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Main Headline", "required": True},
                            ),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("image", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "About Me", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 4), ("content", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "My Services", "required": False},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            9: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("description", 9), ("icon", 2)]],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("services", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Selected Projects", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "Some of my recent projects.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "page_type": ["portfolio.ProjectPage"],
                                    "required": False,
                                },
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 13), ("intro", 14), ("projects", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Get in Touch!",
                                    "help_text": "Contact Me",
                                    "required": True,
                                },
                            ),
                            19: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"default": "Lets work together.", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 18), ("text", 19)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [("menu_item", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to an internal page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link to an external URL",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("link_page", 1), ("link_url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter your email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="Enter your LinkedIn profile URL",
                        null=True,
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, help_text="Enter your GitHub profile URL", null=True
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Enter your Twitter profile URL",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Settings",
                "verbose_name_plural": "Social Media Settings",
            },
        ),
    ]
