# Generated by Django 6.0 on 2026-02-07 15:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "to_address",
                    models.CharField(
                        blank=True,
                        help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                        max_length=255,
                        validators=[wagtail.contrib.forms.models.validate_to_address],
                        verbose_name="to address",
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="from address"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subject"
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                ("thank_you_text", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.forms.models.FormMixin,
                "wagtailcore.page",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 3),
                            ("about", 6),
                            ("services", 12),
                            ("showcase", 18),
                            ("contact", 22),
                            ("contact_form", 24),
                            ("grid", 32),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Main Headline", "required": True},
                            ),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("image", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "About Me", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 4), ("content", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "My Services", "required": False},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            9: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("description", 9), ("icon", 2)]],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("services", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Selected Projects", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "Some of my recent projects.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "page_type": ["portfolio.ProjectPage"],
                                    "required": False,
                                },
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Link to View All", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 13),
                                        ("intro", 14),
                                        ("projects", 16),
                                        ("link_target", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Get in Touch!",
                                    "help_text": "Contact Me",
                                    "required": True,
                                },
                            ),
                            20: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"default": "Lets work together.", "required": False},
                            ),
                            21: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Side illustration image",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 19), ("text", 20), ("illustration", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["home.ContactPage"]},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 8),
                                        ("description", 1),
                                        ("form_page", 23),
                                    ]
                                ],
                                {},
                            ),
                            25: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional Section Heading.",
                                    "required": False,
                                },
                            ),
                            26: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                            27: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            28: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image"},
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 8),
                                        ("description", 1),
                                        ("form_page", 23),
                                    ]
                                ],
                                {"icon": "mail"},
                            ),
                            30: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 26),
                                        ("paragraph", 27),
                                        ("image", 28),
                                        ("contact_form", 29),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"label": "Columns", "max_num": 4, "min_num": 1},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [[("grid_title", 25), ("columns", 31)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 3),
                            ("about", 6),
                            ("services", 12),
                            ("showcase", 18),
                            ("contact", 22),
                            ("contact_form", 24),
                            ("grid", 32),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Main Headline", "required": True},
                            ),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("image", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "About Me", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 4), ("content", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "My Services", "required": False},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            9: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("description", 9), ("icon", 2)]],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("services", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Selected Projects", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "Some of my recent projects.",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "page_type": ["portfolio.ProjectPage"],
                                    "required": False,
                                },
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Link to View All", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 13),
                                        ("intro", 14),
                                        ("projects", 16),
                                        ("link_target", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Get in Touch!",
                                    "help_text": "Contact Me",
                                    "required": True,
                                },
                            ),
                            20: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"default": "Lets work together.", "required": False},
                            ),
                            21: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Side illustration image",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 19), ("text", 20), ("illustration", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["home.ContactPage"]},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 8),
                                        ("description", 1),
                                        ("form_page", 23),
                                    ]
                                ],
                                {},
                            ),
                            25: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional Section Heading.",
                                    "required": False,
                                },
                            ),
                            26: ("wagtail.blocks.CharBlock", (), {"icon": "title"}),
                            27: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            28: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image"},
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 8),
                                        ("description", 1),
                                        ("form_page", 23),
                                    ]
                                ],
                                {"icon": "mail"},
                            ),
                            30: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 26),
                                        ("paragraph", 27),
                                        ("image", 28),
                                        ("contact_form", 29),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"label": "Columns", "max_num": 4, "min_num": 1},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [[("grid_title", 25), ("columns", 31)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Favicon used in the browser tab (recommended 32x32)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Brand logo used in the navbar",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding Settings",
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "clean_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Safe name of the form field, the label converted to ascii_snake_case",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the form field",
                        max_length=255,
                        verbose_name="label",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("singleline", "Single line text"),
                            ("multiline", "Multi-line text"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("url", "URL"),
                            ("checkbox", "Checkbox"),
                            ("checkboxes", "Checkboxes"),
                            ("dropdown", "Drop down"),
                            ("multiselect", "Multiple select"),
                            ("radio", "Radio buttons"),
                            ("date", "Date"),
                            ("datetime", "Date/time"),
                            ("hidden", "Hidden field"),
                        ],
                        max_length=16,
                        verbose_name="field type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="required"),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.",
                        verbose_name="choices",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Default value. Comma or new line separated values supported for checkboxes.",
                        verbose_name="default value",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="help text"
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="home.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [("menu_item", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to an internal page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link to an external URL",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("link_page", 1), ("link_url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter your email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="Enter your LinkedIn profile URL",
                        null=True,
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, help_text="Enter your GitHub profile URL", null=True
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Enter your Twitter profile URL",
                        null=True,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="International format (e.g. +12345234567)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Your username without the @ (e.g. username)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "extra_links",
                    wagtail.fields.StreamField(
                        [("social_link", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. Telegram Channel",
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Upload a logo/icon", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("platform_name", 0), ("url", 1), ("icon", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Settings",
                "verbose_name_plural": "Social Media Settings",
            },
        ),
    ]
